#!/bin/bash
# this could be way cleaner
tree_path=$1
cmd_name=$2
bin_dir=/usr/local/bin
cmd_path=$bin_dir/$cmd_name
here_path="$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd -P)"
full_tree_path=$here_path/$tree_path
cp "$here_path/pushbutton.py" $bin_dir/pushbutton.py

echo '#!/bin/bash' > "$cmd_path"
# N.B. single quotes to avoid expansion here
echo 'PUSHBUTTON_BASENAME=$(basename $0) $(dirname "${BASH_SOURCE[0]}")/pushbutton.py '"$full_tree_path"' "$@"' >> "$cmd_path"
chmod +x "$cmd_path"

echo "Installed pushbutton shim for $tree_path at $cmd_path"
